name: Release-solution-to-DEV-QA
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:

jobs:
  Release_to_DEV_QA:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: solutions/CICDSolution
        solution-file: out/solutions/CICDSolution.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://orgd161aeeb.crm4.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-file: out/solutions/CICDSolution.zip
        force-overwrite: true
        publish-changes: true

