name: Power Platform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Power_Platform_CI_CD:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
        
    - name: Who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        
    - name: Export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: CICDSolution
        solution-output-file: out/exported/CICDSolution.zip
