name: Power Platform CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Power_Platform_CI_CD:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
        
    - name: Who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        
    - name: Export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: CICDSolution
        solution-output-file: out/exported/CICDSolution.zip
        
    - name: Un-pack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/CICDSolution.zip
        solution-folder: out/solutions/CICDSolution
        solution-type: 'Unmanaged'
        overwrite-files: false
        
    - name: Branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/CICDSolution
        solution-target-folder: solutions/CICDSolution
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
