name: WHO
#Export Solution from DEV environment, Branch the exported solution, Export it to PRE-PRODUCTION

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

#Export, Branch Solution and prepare it for PRE-PRODUCTION deployement

jobs:
  Export-and-Branch-Solution:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
   
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Who?
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: https://org8afc7726.crm.dynamics.com/
        app-id: 41098e32-fccf-4145-b353-f40f2a917b16
        client-secret: CEe5HsWm7Rcr2sCQ3puQ87aZty4kE5Iq
        tenant-id: c1d0b961-f301-4256-b2ec-6e9efa04d80b
