name: WHO
#Export Solution from DEV environment, Branch the exported solution, Export it to PRE-PRODUCTION

on:
  workflow_dispatch:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

#Export, Branch Solution and prepare it for PRE-PRODUCTION deployement

jobs:
  Export-and-Branch-Solution:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
   
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: Who?
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: https://org8afc7726.crm.dynamics.com
        app-id: ${{ secrets.APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{ secrets.TENANT_ID }}
